### ISSUE TITLE
How to Read 2 GB file and Parse it

### ISSUE THREAD

**Issue by vnnv01** [RazrFalcon/roxmltree#18]
Hi Team,

Lxml in python is able to read only an element and we can remove it from memory after we parse it. This helps in parsing big file easily without affecting memory.  It has method called iterparse

https://www.ibm.com/developerworks/xml/library/x-hiperfparse/

Is it possible to have something similar , so that we dont need to create a huge string and parse it.

Thanks

**Comment by RazrFalcon** [comment]
Have you considered `memmap`?

`roxmltree` designed for small files in mind, so I'm not sure what exactly you want to change to support large files. Also, I have no idea how lxml handles large files.

The core idea of `roxmltree` is to reduce the number of allocations by reusing an input string as much as possible. So we still need a whole string.

**Comment by dabreegster** [comment]
Sorry to reopen an old issue, but I'm trying to handle a 1GB input. I'm running out of memory (16GB) trying to do this in the naive way.

For starters, I'm not sure I understand why -- a 1GB utf-8 string shouldn't take so much RAM, since [the representation](https://doc.rust-lang.org/std/string/struct.String.html#representation) is just raw bytes.

I'm trying memmap:

```
let f = std::fs::File::open(path)?;
let mmap = unsafe { memmap2::Mmap::map(&f)? };
let x = std::str::from_utf8(&mmap)?;
let doc = roxmltree::Document::parse(x)?;
```

but still OOMing at `str::from_utf8`. This isn't an issue with roxmltree, but in case you have any ideas, it's much appreciated. As you've said here and in #62, this crate is meant for small inputs, so I maybe need to just switch to a streaming reader.

**Comment by RazrFalcon** [comment]
Can you send me the file?

I haven't measured roxmltree overhead, but it should be around 3-4x of the original file. Not good, but not 16GB either.

Ans since it crashes before roxmltree, I would assume something wrong with your file or hardware.

**Comment by dabreegster** [comment]
https://www.dropbox.com/s/2qqv3s5nxs8odi7/greater_london.osm?dl=0
I'm mistaken, reading to a string is fine. It is OOMing during `Document::parse`. This might just be a matter of #63.

**Comment by RazrFalcon** [comment]
Can confirm. It takes 12GB to parse in Release mode. Meaning a 12x overhead. I guess you should wait for #63
