### ISSUE TITLE
Consider public fields of the main structs. 

### ISSUE THREAD

**Issue by dmtrKovalenko** [RazrFalcon/roxmltree#61]
I am working on a macro that parses the XML and from tokentree's and as for now it is not possible to directly output the roxmltree. So while having my custom version of XML ast in the macro I encode it into string and then decode using roxmltree. It would be really great if I can emit something like this right from the macro. 

```rust
    roxmltree::Document {
        text: "",
        nodes: vec![...],
        attrs: vec![...],
        namespaces: vec![...]
    };
```

**Comment by RazrFalcon** [comment]
Well, those fields are an internal implementation and must not be touched. The code is designed around the fact that the content of those fields are correct.

I can make an unsafe constructor, like `Vec::from_raw_parts` if you like. But I don't want any `unsafe` in the code.
Therefore some sort of validation is required, which is expensive and I'm not sure even possible.

Basically, I don't see how we can do this. What are you even trying to achive?

**Comment by dmtrKovalenko** [comment]
I have a macro that defines svg which I then pass to the usvg and using. Here I just trying to optimise parsing of the xml strings

**Comment by RazrFalcon** [comment]
>Isn't it my responsibility to pass the "correct" content?

Only when a function is marked as `unsafe`, which I cannot do because of `#![forbid(unsafe_code)]`. Otherwise we're breaking Rust rules.

I would suggest parsing a string. `roxmltree` is plenty fast and I think you underestimate how complex `roxmltree::Document` is. You must provide correct token spans (token position in the original string), the `NodeId` is pretty unintuitive thanks to `NodeData::next_subtree` and I'm not even sure you would be able to define lifetimes correctly (well, unless your SVG string/input is `'static`).

Not to mention you would have to update your implementation after each `roxmltree` update.

**Comment by dmtrKovalenko** [comment]
I actually think that you have not understand what I expect. Just to add a pub for each field of document and make sure that it is accessible from outside. 

Your library is 0.x so every upgrade is major and thanks to types that will be a my problem. 

> roxmltree is plenty fast

Onless you rendering 100000 similar svg's in parallel.

**Comment by RazrFalcon** [comment]
I cannot "just" mark them as public, because there are a lot of private types (`NodeKind`, `NodeData`, `ExpandedNameOwned`, `Namespaces`, etc.) as well, which I would have to make public. Which I do not plan doing.

You're definitely doing something very strange I do not plan to support this edge-case, sorry.

**Comment by dmtrKovalenko** [comment]
> Which I do not plan doing 

There is really no reason for you to reject doing this. In this case I will basically need to fork your usvg library and maintain my own version of it. Probably a great way reduce an amount of useless code, thanks!

**Comment by RazrFalcon** [comment]
>There is really no reason for you to reject doing this.

I gave you multiple reasons. All of which are technical. 

Here is an another one: as a maintainer, there is really no reason for me to complicate my job by supporting a bizarre edge-case that would be used by a single person.

**Comment by dmtrKovalenko** [comment]
I am sorry, but if you decide to talk in a passive-aggressive way – I would describe your in a language you understand. 

Your design is bad. You expose a public API that is used by another but there is no way to construct the library from scratch. There is no way to test your library without running a whole parser which is not available in no std as well and by doing this you are introducing a dumb limitation for nothing.
