### ISSUE TITLE
Most APIs rather return a `&'a str` than a `Cow<'input, str>`

### ISSUE THREAD

**Issue by benthillerkus** [RazrFalcon/roxmltree#88]
I get that this is a bit more ergonomic, but it also means that users cannot do zero-copy stuff—or need to keep the `Document` around.
I think a solution could be to just make the fields that have Cows public and annotate that this is not a stable API.

**Comment by RazrFalcon** [comment]
Yes, `Cow` will make things more tedious. We could try exposing them using separate API.

**Comment by benthillerkus** [comment]
Would just adding `_cow` or `_from_input` versions of the getters be enough?

I had a bit of a look at the code, and some functions, like `Node::text` have some logic inside that would have to be duplicated. From what I've seen, these are always small enough that just copy pasting would be reasonable imo.
An alternative could be using `BorrowedText<'input, 'a>` from the parser in all data structures instead of Cows, but that would either require pretty much touching every signature in the code base; or writing an additional third set of getters that turn the Cows back into `BorrowedText` at run time and both the `text` and `text_cow` getters would the delegate to such a function

**Comment by adamreichold** [comment]
> Yes, Cow will make things more tedious.

But would it really hurt to change things from `-> &'a str` to `-> &'a Cow<'input, str>`? Since `Cow` implements `Deref`, shouldn't I be able to pass it everywhere a `&'a str` is expected, e.g. https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6ac8c770938f6829317a50a0e02a303f

**Comment by benthillerkus** [comment]
Just doing `&'a Cow<'input, str>` would require all fields that are currently plain `&'input str`s to become Cows, because we cannot just wrap the slice with a `Cow::Borrowed` int the getters as that would then be owned by the function and we cannot return a reference to it.

**Comment by adamreichold** [comment]
> Just doing `&'a Cow<'input, str>` would require all fields that are currently plain `&'input str`s to become Cows, because we cannot just wrap the slice with a `Cow::Borrowed` in the getters and return a reference to these

Could you give an example of the situation you describe? Naively, fields which are `&'input str` would should already be exposed as `&'input str` in the API as there is no reason to narrow them to `&'a str` in the first place.

**Comment by adamreichold** [comment]
(For example, `Attribute::name` yielding `&'a str` instead of `&'input str` is just an oversight which should be corrected.)

**Comment by benthillerkus** [comment]
(oh lol I was gonna mention that)

But I was mostly thinking of this: This function borrows either from the Cows or the input:

https://github.com/RazrFalcon/roxmltree/blob/0b12673528ce049e94d080156e139b59a51dbc05/src/lib.rs#L1082-L1096

```rust
    #[inline]
    pub fn text(&self) -> Option<&'a str> {
        match self.d.kind {
            NodeKind::Element { .. } => match self.first_child() {
                Some(child) if child.is_text() => match self.doc.nodes[child.id.get_usize()].kind {
                    NodeKind::Text(ref text: Cow<'input, str>) => Some(text),
                    _ => None,
                },
                _ => None,
            },
            NodeKind::Comment(text: 'a str) => Some(text),
            NodeKind::Text(ref text: Cow<'input, str>) => Some(text),
            _ => None,
        }
    }
```

Returning `Cow<'input, str>`s would be fine:
```rust
    #[inline]
    pub fn text(&self) -> Option<Cow<'input, str>> {
        match &self.d.kind {
            NodeKind::Element { .. } => match self.first_child() {
                Some(child) if child.is_text() => match self.doc.nodes[child.id.get_usize()].kind {
                    NodeKind::Text(text) => Some(text),
                    _ => None,
                },
                _ => None,
            },
            NodeKind::Comment(text) => Some(Cow::Borrowed(text)), // !
            NodeKind::Text(text) => Some(text),
            _ => None,
        }
    }
```
(*this* exactly might not work, but I had a version of this returning a Cow running this evening.)


But if we were to return `Cow<'input, str>`s this stops working, because we cannot do
`NodeKind::Comment(text) => Some(&Cow::Borrowed(text))`

**Comment by adamreichold** [comment]
I think return `Cow<'input, str>` is not helpful as it means copying in the owned case (meaning there is a `.clone()` call missing in the above).

For that particular example, I think storing `Cow<'input, str>` inside `NodeKind::Coment` instead of `&'input str` is a reasonable price to pay for making this work in the general case.

Another option would be to not return the text of comments here in the first place, at least I have seen code which needs this capability.

**Comment by benthillerkus** [comment]
right, returning an owned Cow makes only sense if the `&'a str` api stays in place, so that the Cow API would aways give you data that outlives the document and the normal API would always give you references.

That being said, if refactoring stuff so that a single `&'a Cow<'input, str>` API is doable, I guess I'd prefer that

**Comment by adamreichold** [comment]
> That being said, if refactoring stuff so that a single &'a Cow<'input, str> API is doable, I guess I'd prefer that

I very much think it is doable and it should mostly be most calls to `.as_ref()` outside of the method implementations. Especially in the case discussed above, making `NodeKind::Comment` always store `Cow::Borrowed` would not even increase any structure sizes as it would only make the `Comment` variant have the same size as the `Text` variant.

**Comment by RazrFalcon** [comment]
@benthillerkus can you provide an example where you would need zero-copy? In my use-case I post-process/parse attributes and text nodes anyway, so it doesn't matter much.

I just don't understand where would you benefit from it. Either way you would have to keep `Document` around.

And adding a `_cow` variant everywhere doesn't look like a good solution either. There current API is already too complex .

**Comment by benthillerkus** [comment]
> @benthillerkus can you provide an example where you would need zero-copy? In my use-case I post-process/parse attributes and text nodes anyway, so it doesn't matter much.
> 
> I just don't understand where would you benefit from it. Either way you would have to keep `Document` around.

I'm using roxmltree to deserialize into a custom data structure. I don't *need* zero-copy, but it would save me from cloning pretty much everything, as I'm not keeping the doc around.

**Comment by RazrFalcon** [comment]
So you what to _take_ a `Cow` from the doc, right? And you still have the input string around as well?
I'm not sure what can be done here. roxmltree simply isn't designed for a case like this. It's immutable.
The idea is that you deserialize the content immediately. This is what I do in [resvg](https://github.com/RazrFalcon/resvg).

**Comment by adamreichold** [comment]
> So you what to take a Cow from the doc, right? 

I think in that case, `clone`ing the `Cow` is sufficient as this operation is cheap when the `Cow` is `Borrowed` and automatically falls back to clong the string content when necessary so that `'input` is the only relevant lifetime.

This is why I proposed providing access to `&'a Cow<'input, str>` as it is sufficient to produce a `Cow<'input, str>` for storage elsewhere which is cheap most of the time. (Taking it would be cheap all of the time, but as you say this goes against immutability and internal sharing.)

**Comment by RazrFalcon** [comment]
The problem with Cow, excluding the ugly API, is that its "cheapness" vary depending on a file. Remember that we do preprocess attribute values and text nodes.

As an example, base64-encoded data in SVG, aka raster images, is often split into multiple lines. So it will be preprocessed and allocated as a String. But this can easily be a multi MB data block. Cloning it is not cheap. This is there rationale behind #65

The only way to "fix" this is by allowing to take the data from `Document`, which is not possible, since it's immutable.
If one cares about the performance, they should use a streaming parser to begin with. roxmltree should prioritize nicer APi to performance.

**Comment by benthillerkus** [comment]
> As an example, base64-encoded data in SVG, aka raster images, is often split into multiple lines. So it will be preprocessed and allocated as a String. But this can easily be a multi MB data block. Cloning it is not cheap. This is there rationale behind #65
> 
> The only way to "fix" this is by allowing to take the data from `Document`, which is not possible, since it's immutable.

I'm not 100% sure I understand the concern, but assuming there was an API that returned `&'a Cow<_>`s, one would have all three options and be able to pick what's best suited for their use case.

**Comment by adamreichold** [comment]
> I'm not 100% sure I understand the concern, but assuming there was an API that returned &'a Cow<_>s, one would have all three options and be able to pick what's best suited for their use case.

Basically, the API offering `&'a Cow` is bad in two dimensions: ergonomics due things like `Option<&'a Cow>` not automatically coercing to `Option<&'a str>` and because its performance profile is very uneven and depends on the input (whether it needs normalization or not).

Note that you don't have the "third option" (moving out the `Cow` without copying anything) as we could only provide a shared reference from which you could not move. This is intrinsic to the design as the library tries to share as much data as possible internally and with the original input, so that reference `&'a Cow` might really be shared with other parts of the `Document` and modification would modify all usages.

**Comment by RazrFalcon** [comment]
The other option is to use shared strings, aka `Rc<Cow<str>>`. This way one can drop `Document` early. But this would be an even more complex change and uglier API. Would hurt performance, at least in theory due to indirection. And kinda unidiomatic behavior.

**Comment by benthillerkus** [comment]
Ah ok, I didn't realise that roxmltree itself already tries to reuse its additional allocations.

I guess in theory it could be possible to turn the String type used into a generic parameter of Document, but yeah...

**Comment by RazrFalcon** [comment]
You can use `*_storage()` methods now, which results would outlive the document. Hopefully this is what you want.
