### ISSUE TITLE
Add Node::children_elements

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/roxmltree#91]

**Comment by RazrFalcon** [comment]
@adamreichold I think it would be a great idea to have elements-only alternative for all of our iterators. If you're interested in it.

**Comment by adamreichold** [comment]
> @adamreichold I think it would be a great idea to have elements-only alternative for all of our iterators. If you're interested in it.

I am somewhat undecided whether I think this is a good idea. In my usage of roxmltree, I repeatedly wondered whether I would create a set of generic iteration/extraction functions on top of the iterator-based API. But in the end, just working with the iterators was simple enough.

If we start adding such convenience API to roxmltree, when do we stop? The most reasonable choice I see ATM is to add only stuff that benefits from having access to the crate's internals. But due to `.children().filter(|node| node.is_elment())` being simple enough, I don't think `children_elements` would pass that test.

One alternative I could get behind is/was #70, i.e. adding an optional dependency here on `simplecss` to add a feature gated

```
Node::select(&self, &Selector) -> impl Iterator<Item=&Node>;
```

because this would be a more fundamental improvement of expressive power. Of course, as you mentioned in #70, the same issue of "Where to stop" would then exist for `simplecss` as the feature requests start coming in over there...

**Comment by RazrFalcon** [comment]
Yep, I completely forgot about it. You're suppose to use iterators for this. That was the original design goal.
Yes, a bit more verbose, but much more flexible. 

We do have some `Node::*_element` methods, like `first_element_child`, but having dedicated iterators would probably be an overkill. 

I do consider `roxmltree` to be feature complete and there is no need for CSS query and other stuff. It's already too complicated for my taste, but this is mainly due to inherent complexity of XML.
